apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of existing files here
resources:
- docker-deployment.yml
- docker_jobs_deployment.yml
- configmap.yaml

# allows GitHub Action to update the image tags
images:
- name: ghcr.io/annackk/rag-api
  newName: <YOUR_AWS_ID>.dkr.ecr.eu-west-1.amazonaws.com/rag-api
- name: ghcr.io/annackk/rag-dashboard
  newName: <YOUR_AWS_ID>.dkr.ecr.eu-west-1.amazonaws.com/rag-dashboard
- name: ghcr.io/annackk/data_processing
  newName: <YOUR_AWS_ID>.dkr.ecr.eu-west-1.amazonaws.com/data_processing
